apiVersion: apps/v1  # Specifies Kubernetes API version
kind: Deployment  # Defines the type of resource
metadata:
  name: devops-app  # Name of the deployment
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: devops-app  # Defines pod labels to match
  template:
    metadata:
      labels:
        app: devops-app  # Label to identify pods
    spec:
      containers:
        - name: devops-app-container  # Name of the container
          image: 536697270964.dkr.ecr.us-east-1.amazonaws.com/ecr-container-repo:c7cf3c84b56c4cee93283976b624af42117af4c4
          ports:
            - containerPort: 80  # Exposing port