apiVersion: v1
kind: Service
metadata:
  name: devops-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use Network Load Balancer
  labels:
    app: devops-app  
spec:
  type: LoadBalancer
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
